import type {
  User,
  SealApplication,
  Seal,
  SealRegistration,
  ApprovalRecord,
} from './types';

export const mockUsers: User[] = [
  {
    id: 'u001',
    name: '张伟',
    role: 'employee',
    department: '市场部',
    email: 'zhangwei@company.com',
  },
  {
    id: 'u002',
    name: '李娜',
    role: 'dept_head',
    department: '市场部',
    email: 'lina@company.com',
  },
  {
    id: 'u003',
    name: '王强',
    role: 'leader',
    department: '总经办',
    email: 'wangqiang@company.com',
  },
  {
    id: 'u004',
    name: '陈静',
    role: 'seal_admin',
    department: '行政部',
    email: 'chenjing@company.com',
  },
  {
    id: 'u005',
    name: '刘洋',
    role: 'admin',
    department: '信息部',
    email: 'liuyang@company.com',
  },
];

const now = new Date();
const daysAgo = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};
const daysLater = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  return d.toISOString();
};

export const mockApprovalRecords: ApprovalRecord[] = [
  {
    id: 'ar001',
    applicationId: 'app001',
    node: 'submitter',
    approverId: 'u001',
    approverName: '张伟',
    action: 'submit',
    opinion: '申请用印，请审批。',
    timestamp: daysAgo(10),
  },
  {
    id: 'ar002',
    applicationId: 'app001',
    node: 'dept_head',
    approverId: 'u002',
    approverName: '李娜',
    action: 'approve',
    opinion: '同意',
    timestamp: daysAgo(9),
  },
  {
    id: 'ar003',
    applicationId: 'app001',
    node: 'leader',
    approverId: 'u003',
    approverName: '王强',
    action: 'approve',
    opinion: '同意，按流程办理。',
    timestamp: daysAgo(8),
  },
  {
    id: 'ar004',
    applicationId: 'app002',
    node: 'submitter',
    approverId: 'u001',
    approverName: '张伟',
    action: 'submit',
    opinion: '合同用印申请。',
    timestamp: daysAgo(7),
  },
  {
    id: 'ar005',
    applicationId: 'app002',
    node: 'dept_head',
    approverId: 'u002',
    approverName: '李娜',
    action: 'approve',
    opinion: '同意',
    timestamp: daysAgo(6),
  },
  {
    id: 'ar006',
    applicationId: 'app003',
    node: 'submitter',
    approverId: 'u001',
    approverName: '张伟',
    action: 'submit',
    opinion: '项目文件用印。',
    timestamp: daysAgo(5),
  },
  {
    id: 'ar007',
    applicationId: 'app003',
    node: 'dept_head',
    approverId: 'u002',
    approverName: '李娜',
    action: 'reject',
    opinion: '材料不齐全，请补充。',
    timestamp: daysAgo(4),
  },
  {
    id: 'ar008',
    applicationId: 'app004',
    node: 'submitter',
    approverId: 'u001',
    approverName: '张伟',
    action: 'submit',
    opinion: '招标文件用印申请。',
    timestamp: daysAgo(3),
  },
  {
    id: 'ar009',
    applicationId: 'app005',
    node: 'submitter',
    approverId: 'u001',
    approverName: '张伟',
    action: 'submit',
    opinion: '介绍信用印。',
    timestamp: daysAgo(2),
  },
  {
    id: 'ar010',
    applicationId: 'app005',
    node: 'dept_head',
    approverId: 'u002',
    approverName: '李娜',
    action: 'approve',
    opinion: '同意',
    timestamp: daysAgo(1),
  },
];

export const mockApplications: SealApplication[] = [
  {
    id: 'app001',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '公章',
    sealId: 's001',
    reason: '与客户签订年度合作协议',
    documentName: '2026年度合作框架协议.pdf',
    quantity: 2,
    urgency: 'normal',
    status: 'registered',
    currentNode: 'leader',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(7),
    approvalTrail: mockApprovalRecords.filter((r) => r.applicationId === 'app001'),
  },
  {
    id: 'app002',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '合同专用章',
    sealId: 's002',
    reason: '采购合同签订',
    documentName: '办公设备采购合同.pdf',
    quantity: 1,
    urgency: 'urgent',
    status: 'pending_leader',
    currentNode: 'leader',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
    approvalTrail: mockApprovalRecords.filter((r) => r.applicationId === 'app002'),
  },
  {
    id: 'app003',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '公章',
    reason: '项目申报材料',
    documentName: '科技创新项目申报书.docx',
    quantity: 5,
    urgency: 'normal',
    status: 'rejected',
    currentNode: 'submitter',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    approvalTrail: mockApprovalRecords.filter((r) => r.applicationId === 'app003'),
  },
  {
    id: 'app004',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '公章',
    reason: '政府项目投标',
    documentName: '智慧城市项目投标文件.pdf',
    quantity: 10,
    urgency: 'emergency',
    status: 'pending_dept',
    currentNode: 'dept_head',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    approvalTrail: mockApprovalRecords.filter((r) => r.applicationId === 'app004'),
  },
  {
    id: 'app005',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '法人章',
    reason: '银行开户手续',
    documentName: '银行开户授权书.pdf',
    quantity: 1,
    urgency: 'urgent',
    status: 'pending_leader',
    currentNode: 'leader',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    approvalTrail: mockApprovalRecords.filter((r) => r.applicationId === 'app005'),
  },
  {
    id: 'app006',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '财务专用章',
    reason: '发票开具',
    documentName: '开票申请单.xlsx',
    quantity: 3,
    urgency: 'normal',
    status: 'draft',
    currentNode: 'submitter',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    approvalTrail: [],
  },
  {
    id: 'app007',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '公章',
    sealId: 's001',
    reason: '资质证明文件',
    documentName: '企业资质证明.pdf',
    quantity: 2,
    urgency: 'normal',
    status: 'approved',
    currentNode: 'leader',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
    approvalTrail: [
      {
        id: 'ar011',
        applicationId: 'app007',
        node: 'submitter',
        approverId: 'u001',
        approverName: '张伟',
        action: 'submit',
        opinion: '资质证明用印。',
        timestamp: daysAgo(6),
      },
      {
        id: 'ar012',
        applicationId: 'app007',
        node: 'dept_head',
        approverId: 'u002',
        approverName: '李娜',
        action: 'approve',
        opinion: '同意',
        timestamp: daysAgo(5),
      },
      {
        id: 'ar013',
        applicationId: 'app007',
        node: 'leader',
        approverId: 'u003',
        approverName: '王强',
        action: 'approve',
        opinion: '同意',
        timestamp: daysAgo(4),
      },
    ],
  },
  {
    id: 'app008',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '合同专用章',
    reason: '租赁合同',
    documentName: '办公场地租赁合同.pdf',
    quantity: 4,
    urgency: 'normal',
    status: 'cancelled',
    currentNode: 'submitter',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(12),
    approvalTrail: [],
  },
  {
    id: 'app009',
    applicantId: 'u001',
    applicantName: '张伟',
    department: '市场部',
    sealType: '公章',
    sealId: 's001',
    reason: '工商年检材料',
    documentName: '工商年检报告书.pdf',
    quantity: 1,
    urgency: 'normal',
    status: 'registered',
    currentNode: 'leader',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(15),
    approvalTrail: [
      {
        id: 'ar014',
        applicationId: 'app009',
        node: 'submitter',
        approverId: 'u001',
        approverName: '张伟',
        action: 'submit',
        opinion: '年检材料用印。',
        timestamp: daysAgo(20),
      },
      {
        id: 'ar015',
        applicationId: 'app009',
        node: 'dept_head',
        approverId: 'u002',
        approverName: '李娜',
        action: 'approve',
        opinion: '同意',
        timestamp: daysAgo(19),
      },
      {
        id: 'ar016',
        applicationId: 'app009',
        node: 'leader',
        approverId: 'u003',
        approverName: '王强',
        action: 'approve',
        opinion: '同意',
        timestamp: daysAgo(18),
      },
    ],
  },
];

export const mockSeals: Seal[] = [
  {
    id: 's001',
    batchNumber: 'BATCH-2025-001',
    sealType: '公章',
    serialNumber: 'GZ-2025-0001',
    receivedDate: daysAgo(365),
    expiryDate: daysLater(180),
    status: 'in_use',
    custodian: '陈静',
    enableDate: daysAgo(360),
    remark: '公司法定名称公章',
  },
  {
    id: 's002',
    batchNumber: 'BATCH-2025-002',
    sealType: '合同专用章',
    serialNumber: 'HT-2025-0001',
    receivedDate: daysAgo(300),
    expiryDate: daysLater(60),
    status: 'warning',
    custodian: '陈静',
    enableDate: daysAgo(295),
    remark: '即将到期，需提前办理续期',
  },
  {
    id: 's003',
    batchNumber: 'BATCH-2025-003',
    sealType: '财务专用章',
    serialNumber: 'CW-2025-0001',
    receivedDate: daysAgo(400),
    expiryDate: daysAgo(30),
    status: 'expired',
    custodian: '陈静',
    enableDate: daysAgo(395),
    remark: '已过期，需更换新章',
  },
  {
    id: 's004',
    batchNumber: 'BATCH-2025-004',
    sealType: '法人章',
    serialNumber: 'FR-2025-0001',
    receivedDate: daysAgo(200),
    expiryDate: daysLater(165),
    status: 'in_use',
    custodian: '陈静',
    enableDate: daysAgo(195),
  },
  {
    id: 's005',
    batchNumber: 'BATCH-2026-001',
    sealType: '财务专用章',
    serialNumber: 'CW-2026-0001',
    receivedDate: daysAgo(10),
    expiryDate: daysLater(355),
    status: 'stored',
    custodian: '陈静',
    remark: '新章入库，待启用',
  },
  {
    id: 's006',
    batchNumber: 'BATCH-2024-005',
    sealType: '发票专用章',
    serialNumber: 'FP-2024-0001',
    receivedDate: daysAgo(500),
    expiryDate: daysAgo(100),
    status: 'expired',
    custodian: '陈静',
    enableDate: daysAgo(490),
    remark: '已过期作废',
  },
  {
    id: 's007',
    batchNumber: 'BATCH-2025-006',
    sealType: '发票专用章',
    serialNumber: 'FP-2025-0001',
    receivedDate: daysAgo(150),
    expiryDate: daysLater(215),
    status: 'in_use',
    custodian: '陈静',
    enableDate: daysAgo(145),
  },
];

export const mockRegistrations: SealRegistration[] = [
  {
    id: 'reg001',
    applicationId: 'app001',
    sealId: 's001',
    registrarId: 'u004',
    registrarName: '陈静',
    registrant: '张伟',
    registrantDepartment: '市场部',
    usageTime: daysAgo(7),
    remark: '已按规定登记',
    createdAt: daysAgo(7),
  },
  {
    id: 'reg002',
    applicationId: 'app009',
    sealId: 's001',
    registrarId: 'u004',
    registrarName: '陈静',
    registrant: '张伟',
    registrantDepartment: '市场部',
    usageTime: daysAgo(15),
    createdAt: daysAgo(15),
  },
  {
    id: 'reg003',
    applicationId: 'app001',
    sealId: 's001',
    registrarId: 'u004',
    registrarName: '陈静',
    registrant: '张伟',
    registrantDepartment: '市场部',
    usageTime: daysAgo(6),
    remark: '两份文件用印',
    createdAt: daysAgo(6),
  },
  {
    id: 'reg004',
    applicationId: 'app009',
    sealId: 's001',
    registrarId: 'u004',
    registrarName: '陈静',
    registrant: '张伟',
    registrantDepartment: '市场部',
    usageTime: daysAgo(14),
    createdAt: daysAgo(14),
  },
  {
    id: 'reg005',
    applicationId: 'app001',
    sealId: 's004',
    registrarId: 'u004',
    registrarName: '陈静',
    registrant: '张伟',
    registrantDepartment: '市场部',
    usageTime: daysAgo(5),
    remark: '法人章使用登记',
    createdAt: daysAgo(5),
  },
];
